### ISSUE TITLE
Duygusal

### ISSUE THREAD

**Issue by frknbasaran** [co3moz/iyikidogdun.be#1]
Duygusal bir çalışma olmuş, özellikle örnek isimlerde adımı görünce arkada şu parça çalmaya başladı. 
https://www.youtube.com/watch?v=St5T6HbBVAc
Başarılarının devamını dilerim.

**Comment by co3moz** [comment]
Yaşlı amca/teyzelerin facebook'ta yaptıkları yorumlar gibi olmuş :smile: 

> Başarıların devamını dilerim.
